name: Run Crypto Analysis Task

on:
  schedule:
    - cron: '30 * * * *' # Saatte bir, her saatin 30. dakikasında çalışır
  workflow_dispatch: # Manuel çalıştırma butonu ekler

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analysis task
        run: python task.py

      - name: Commit results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add results.json
          git commit -m "Update analysis results" || echo "No changes to commit"
          git push
